### PR TITLE
doc-ja: sync up with changes until 5acfd06

### PR DESCRIPTION
**Pull request by osayama**
I updated ja contents for man pages. Could you please check them and merge if they are ok? Also it would be great if these ja contents can be seen through https://linbit.com/man-ja/v9/ and https://linbit.com/man-ja/v84/.

### CODE REVIEW

**Comment by rck** [comment]
Thanks! I have to coordinate the web page changes with the web team, let's see how that works out. and when.

**Comment by osayama** [comment]
I can see ja man pages under
https://linbit.com/man/drbd-9-0-ja/
https://linbit.com/man/drbd-8-4-ja/
Thank you for working !!

**Comment by osayama** [comment]
@rck 
Currently I cannot see 8.4 ja man pages. "404" message is displayed. Do you know what is a problem?
     https://linbit.com/man/drbd-8-4-ja/

**Comment by rck** [comment]
I told the web team, let's hope for the best :)

**Comment by osayama** [comment]
I can see now. Thanks!

**Pull request merged**
