### PR TITLE
maketest : adjusted sed check against timestamp

### PR DESCRIPTION
**Pull request by jtiltx**
Adding pull request to address sed check see #34

### CODE REVIEW

**Review by rck — CHANGES_REQUESTED** [review]
@jtiltx can you update that MR with a proper name and a proper commit message, I'm not going to take something from "root"...

@JoelColledge I think this is your code, was the `+` meant to be escpaced/literal?

**Comment by rck** [comment]
and out of curiosity, @jtiltx what kind of `sed`/version/distribution are you using that this triggers?

**Comment by rck** [comment]
ah, @JoelColledge next guess would be this is actually a locale issue... If so, we should set some `LC_ALL` and friends

**Comment by JoelColledge** [comment]
> @JoelColledge I think this is your code, was the `+` meant to be escpaced/literal?

`+` is a literal. We're calling `sed` without `-E` so `+` without a backslash matches a literal `+`.

> ah, @JoelColledge next guess would be this is actually a locale issue... If so, we should set some LC_ALL and friends

This is my suspicion too.

**Comment by rck** [comment]
reproducer: `TZ=America/Lima make test`

**Comment by rck** [comment]
@jtiltx thanks, we found a reproducer, it is actually a time zone issue, so we can not take you patch as it would break it for other time zones (like mine :) ). we will prepare a patch that will supersede this MR, but thanks for reporting and taking the effort

**Comment by rck** [comment]
should be fixed in https://github.com/LINBIT/drbd-utils/commit/fc49473cde48a9b2bb645ad042abfc56ce2e2e2f

**Pull request closed without merging**
